-- HERE ALL PRACTICE QUERIES ARE WRITTEN FOR TCL (Transaction Control Language) OPERATIONS

1. --COMMIT
CREATE TABLE demo_tcl(
	empno INT,
	ename VARCHAR(30),
	sal NUMERIC(10,2),
	deptno INTEGER
); 
    -- AUTOMATICALLY COMMIT IN ORACLE/MYSQL BUT NOT IN POSTGRE-SQL THE TABLE CREATION 
    -- BECAUSE OF DDL OPERATION

INSERT INTO demo_tcl        
VALUES
(111,'ABC',4000,10),
(112,'DEF',2506.55,20),
(113,'GHI',5203.94,10),
(114,'JKL',3000,40),
(115,'MNO',2000.00,30);

COMMIT;  
    -- COMMIT WILL SAVE THE CHANGES MADE BY INSERT OPERATION

2. --ROLLBACK
UPDATE demo_tcl
SET sal = 5423.21
WHERE empno = 115;

DELETE FROM demo_tcl
WHERE empno = 114;

ROLLBACK;
SELECT * FROM demo_tcl; 
    -- ROLLBACK WILL REVERT THE UPDATE AND DELETE OPERATIONS, SO THE RECORDS WILL BE 
    -- AS THEY WERE BEFORE THE UPDATE AND DELETE

3. --SAVEPOINT
BEGIN;
SAVEPOINT X;
UPDATE demo_tcl
SET sal = 2125.35
WHERE empno = 115;
SAVEPOINT Y;
    -- SAVEPOINT WILL CREATE A POINT IN THE TRANSACTION TO WHICH YOU CAN ROLLBACK

4. --ROLLBACK TO SAVEPOINT
ROLLBACK TO SAVEPOINT X;
    -- ROLLBACK TO SAVEPOINT X WILL REVERT THE UPDATE OPERATION DONE AFTER SAVEPOINT X,
    -- SO THE RECORDS WILL BE AS THEY WERE BEFORE THE UPDATE

BEGIN;
SAVEPOINT X;
UPDATE demo_tcl
SET sal = 5000
WHERE empno = 115;
SAVEPOINT Y;
BEGIN;
DELETE FROM demo_tcl
WHERE empno = 115;
ROLLBACK TO SAVEPOINT X;
    -- ROLLBACK TO SAVEPOINT X WILL REVERT THE DELETE OPERATION DONE AFTER SAVEPOINT X,
    -- SO THE RECORDS WILL BE AS THEY WERE BEFORE THE UPDATE AND DELETE OPERATIONS

BEGIN;
SAVEPOINT X;
UPDATE demo_tcl
SET sal = 5000
WHERE empno = 115;
SAVEPOINT Y;
DELETE FROM demo_tcl
WHERE empno = 115;
ROLLBACK TO SAVEPOINT Y;
    -- ROLLBACK TO SAVEPOINT Y WILL REVERT THE DELETE OPERATION DONE AFTER SAVEPOINT Y,
    -- SO THE RECORDS WILL BE AS THEY WERE BEFORE THE DELETE OPERATION 
    -- BUT THE UPDATE OPERATION DONE AFTER SAVEPOINT X WILL REMAIN AS IT IS

BEGIN;
SAVEPOINT Y;
UPDATE demo_tcl
SET deptno = 20
WHERE empno = 114;

COMMIT;

DELETE FROM demo_tcl
WHERE ename = 'ABC';
ROLLBACK TO SAVEPOINT Y;
    -- SAVEPOINT Y DOES NOT EXIST ANYMORE BECAUSE OF COMMIT,
    -- SO ROLLBACK TO SAVEPOINT Y WILL GIVE ERRORS

BEGIN;
SAVEPOINT X;
ALTER TABLE demo_tcl
RENAME COLUMN ename to emp_name;
SAVEPOINT Y;

ROLLBACK TO X;
    -- ROLLBACK TO SAVEPOINT X WILL REVERT THE ALTER TABLE OPERATION DONE AFTER SAVEPOINT X,
    -- SO THE COLUMN NAME WILL BE AS IT WAS BEFORE THE ALTER TABLE OPERATION
    